### ISSUE TITLE
Model Page Not Found

### ISSUE THREAD

**Issue by BreadPeanutButter** [sibozhang/Text2Video#1]
Thank you for sharing your code. 
https://github.com/alphacep/vosk-api/blob/master/doc/models.md for downloading the model is not found.

**Comment by iAlexKai** [comment]
> Thank you for sharing your code.
> https://github.com/alphacep/vosk-api/blob/master/doc/models.md for downloading the model is not found.

+1

**Comment by sibozhang** [comment]
Please download vosk from https://alphacephei.com/vosk/install
