### ISSUE TITLE
about fetching model 

### ISSUE THREAD

**Issue by iamhere1** [sibozhang/Text2Video#12]
Hi, it's really a great work of your job for converting text to audio.  However, I can not download the model from the address you published(https://www.dropbox.com/sh/lk6et49v2uyfzjx/AADAFAp02_b3FQchaYxOZ0EMa?dl=0). Could you put your model on a place that we can easily get(such as baidu network disk or other network dist we can easily accessed from China)?  Thanks a lot!

**Comment by sibozhang** [comment]
VidTIMIT fadg0 (English, Female) [Dropbox](https://www.dropbox.com/sh/lk6et49v2uyfzjx/AADAFAp02_b3FQchaYxOZ0EMa?dl=0)

百度云链接:https://pan.baidu.com/s/1L1cvqwLu_uqN2cbW-bDgdA 密码:hygt

Xuesong (Chinese, Male) [Dropbox](https://www.dropbox.com/sh/qz3zoma5ac9mw5p/AAARiR8xKvATN4CBSyjWt_uOa?dl=0)

百度云链接:https://pan.baidu.com/s/1lhYRakZLnkQ8nqMuLJt_dA 密码:40ob

**Comment by iamhere1** [comment]
Thanks a lot!

**Comment by iamhere1** [comment]
Hi, @sibozhang 模型看上去是空的？
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/8308024/194795041-f86c32ac-c7ee-460a-8360-13361bfa1194.png">

**Comment by sibozhang** [comment]
重新上传了

**Comment by iamhere1** [comment]
辛苦，不过好像"Xuesong (Chinese, Male)" 对应的链接显示模型已删除，我后来借助 fq 工具从Dropbox下载了。
非常感谢！
