### ISSUE TITLE
English pretrained model not downloadable

### ISSUE THREAD

**Issue by nlune** [sibozhang/Text2Video#16]
Can you please provide the pretrained model via a different platform, like Google drive or something more accessible? I am not able to download it normally on Baidu.

**Comment by sibozhang** [comment]
VidTIMIT fadg0 (English, Female)

Dropbox: https://www.dropbox.com/sh/lk6et49v2uyfzjx/AADAFAp02_b3FQchaYxOZ0EMa?dl=0

Xuesong (Chinese, Male)

Dropbox: https://www.dropbox.com/sh/qz3zoma5ac9mw5p/AAARiR8xKvATN4CBSyjWt_uOa?dl=0

**Comment by nlune** [comment]
Thank you :)
