### ISSUE TITLE
Ho do I train with my own data ?

### ISSUE THREAD

**Issue by Unmesh28** [sibozhang/Text2Video#8]
Hi, Your work seems amazing. I was looking to train it for my own dataset of only one character.
Can you please share detailed instructions for training ? 

Thank You.

**Comment by untszlung** [comment]
I would also like to know how to train my own dataset. Thank you

**Comment by raymond00000** [comment]
this work sounds great!
I would also like to know how to train with my own data. 
Thank you so much.

**Comment by sibozhang** [comment]
Train you own data part is added
